import Head from "next/head";
// import Image from 'next/image'
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>{`<HuntingCoder />`}</h1>
        {/* <Image className={styles.myImg} src="/homeimg.jpg" alt="" height={158} width={237} /> */}
        <img
          className={styles.myImg}
          src="/homeimg.jpg"
          alt=""
          height={237}
          width={237}
        />

        <div className="blogs">
          <h2 className={styles.h2}>Popular blogs</h2>
          <div className="blogItem">
            <h3>Hwo to learn JS in 2022?</h3>
            <p>Js is best language</p>
          </div>
          <div className="blogItem">
            <h3>Hwo to learn JS in 2022?</h3>
            <p>Js is best language</p>
          </div>
          <div className="blogItem">
            <h3>Hwo to learn JS in 2022?</h3>
            <p>Js is best language</p>
          </div>
        </div>
      </main>
    </div>
  );
}
