import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <style jsx>
      {
        `
        
        `
      }
    </style>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.content}>
        Hunting Coder
        </h1>
        <Image className={styles.myImg} src="/homeimg.jpg" alt="" height={158} width={237} />

        <p className={styles.description}>
          A coders blog from a coder
        </p>

        <div className="blogs">
          <h2>Popular blogs</h2>
          <div className="blogItem">
            <h3>Hwo to learn JS in 2022?</h3>
            <p>Js is best language</p>
          </div>
          <div className="blogItem">
            <h3>Hwo to learn JS in 2022?</h3>
            <p>Js is best language</p>
          </div>
          <div className="blogItem">
            <h3>Hwo to learn JS in 2022?</h3>
            <p>Js is best language</p>
          </div>
        </div>
      </main>
    </div>
  )
}
